AllCops:
  TargetRubyVersion: 2.3
  Exclude:
  - 'gemfile'
  - 'bin/**'
  - 'exe/**'
  - 'Gemfile'
  - 'Rakefile'
  - '*.gemspec'
  - 'spec/**/*.rb'
Metrics/LineLength:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false
